### ISSUE TITLE
DMA mode takes up 60k of ram just for a single 300 led strip!!!!!

### ISSUE THREAD

**Issue by chrisdoel** [hpwit/I2SClocklessLedDriver#11]
Hi, this library is absolutely perfect for me. I've been experiencing many issues with glitching when using BLE and driving LEDs at the same time. However, when I define FULL_DMA_BUFFER, 60kB of ram is consumed and I am already running low on ram on this project :(

Is this caused by a bug? I understand that we need 3x the bytes of the led strip data, but in my case this would be less than 1kB

**Comment by hpwit** [comment]
Hello sorry for the late reply
the FULL_DMA is indeed memory hungry.
THe DMA size should be nb_of_leds_per_strip*3*8*2 hence in your case 14k  this is strangethat you have 60k can you share your code ?
I will have a closer look at it maybe I have a mistep somewhere

**Comment by jagspaul** [comment]
I2S1 support to 8 pins. so if we need up to 8 parallel data and we use I2S 1 instead 0 then we can use save 50% memory.

DMA size should be nb_of_leds_per_strip x 3 x 8  x 3

pls guide me how to use I2S 1 in this driver?

thanks

**Comment by jagspaul** [comment]
For existing 16 bit width driver (I2S 0) with FULL_DMA, what is the maximum limit of nb_of_leds_per_strip?

Can I go for 1024 or 2048 Leds per strip?

Thanks & regards

**Comment by hpwit** [comment]
Hello if you’re using full dma buffer it will depend of your memory.

**Comment by hpwit** [comment]
HelloIt’s not responsible of the i2s used. I need a change of code to not use 16 but 8 buffer size. I can make it a choice. YvesOn 2 Jul 2023, at 07:51, Jagadish Paul ***@***.***> wrote:﻿
I2S1 support to 8 pins. so if we need up to 8 parallel data and we use I2S 1 instead 0 then we can use save 50% memory.
DMA size should be nb_of_leds_per_strip x 3 x 8  x 3
pls guide me how to use I2S 1 in this driver?
thanks

**Comment by jagspaul** [comment]
Sorry for not to understand your reply correctly.
1. Did you mean that it is not possible to use I2S 1 instead I2s 0. if so then can you explain the reason? As per my knowledge I2S 1 has a offset of pin from I2S 0. Other things almost same.
2. Are you going to change you code in such a manner that with I2S 0 & within 8 strip you will manage the code it use 8 bit buffer instead of 16 bit?
Thnaks

**Comment by jagspaul** [comment]
> ill depend of your memor

I want to know value of nb_of_leds_per_strip for existin memory of ESP32.

**Comment by hpwit** [comment]
If you use full dma I think around 2200leds per strip

**Comment by hpwit** [comment]
Can I ask you what you are trying to achieve?

**Comment by jagspaul** [comment]
full dma I think around 2200leds per strip

It sounds good.

I will to build 8 data parallel controller with 2048 pixels per data line.
Total capacity 16k pixels.

**Comment by hpwit** [comment]
If you do this you will to have enough ram for much of the rest.
Can I suggest 2 things ?
1) use the Virtual driver to use more pins and have a better refresh rate because now you're refresh rate is 16fps !! without counting the time to transpose the entire screen.
2) do not use full dma buffer in your case
3) if you're afraid that you will have interrupt issues look at this https://youtu.be/sYtVOU8Hpss
If I may ask what will this will be used for ?

**Comment by jagspaul** [comment]
Thanks for you reply.

I will try as you suggested.

Sir one question I have.

Can you explain please how frame rate increase in virtual driver rather
than direct parallel driver?

As I understand in both the cases matrix transpose is done.

Thanks and regards

**Comment by hpwit** [comment]
Hello
The frame rate increases because you can have more parallel pins. I a nutshell the virtual driver allows you to drive 8 strips individually per pin of the esp32 using a shift register. 
Hence you can drive your 16k less over 32 strips of 512 leds. Using 6 pins of the esp32 (4 data 1 latch 1data) Hence the fps will be 65 instead of 16.

**Comment by jagspaul** [comment]
Ok, thanks for the clarification.
