### ISSUE TITLE
Output is timed for 32bit pixels

### ISSUE THREAD

**Issue by peragwin** [hpwit/I2SClocklessLedDriver#6]
Hey, I noticed the framerate to be less than what I would have expected for 24bit/pixel leds. I was able to confirm on the scope what looks like the 24 bits being sent within a 32 bit sized window. I'm guessing this would be to accommodate timing for 32 bit RGBW, but is there a way to disable this to get a higher framerate?

I'm sure I can figure it out if I keep digging, but the DMA+transposition code is a little bit obtuse. I would appreciate a quick pointer if you had one!

![IMG_1554](https://user-images.githubusercontent.com/6548205/170772192-45fb2c7f-c54d-4dc8-97fa-5530754f904b.jpg)

**Comment by hpwit** [comment]
Hello that is really strange. 
this should not happen. Did you activate rgbw ?
Can you send me your code
In the meantime I will look at the driver.

**Comment by hpwit** [comment]
How many strips are you using ?
Use this commit 
https://github.com/hpwit/I2SClocklessLedDriver/tree/87a67af8b39090fe254a45308c72386e11bc85a6
and let me know. 
this commit does not have the hardware scrolling

**Comment by hpwit** [comment]
Hello
I have  checked the pulses with my logic analyser and the latest commit of the library and I don't have any issue,
below the analyser for 5 pixels. and you can see no 'blank' between pixels. and we have well 5*24=120 pulses


![Capture d’écran 2022-05-28 à 10 41 20](https://user-images.githubusercontent.com/7348175/170818095-d80c56bc-a161-4ad7-a139-7c73233f8a01.png)


here is using the gettingstartedFastLED the results of the fps (16 strips in parrallel)
![Capture d’écran 2022-05-28 à 10 57 14](https://user-images.githubusercontent.com/7348175/170818505-38f69238-68c9-44f1-9b50-abb490a9800d.png)

you can see at low number of leds per strip there is an issue due to the overhead. (which is the same regardless of the number of leds)
let me know how many leds per strip and the code you have
rgds
Yves

**Comment by peragwin** [comment]
Hey thanks so much for looking into this!

I wasn't able to get to my lab yesterday to try things, but I'm looking through my code. I'm doing some things weird maybe because I'm trying to combine your Clockless and ClockBased drivers into the same library for my project. See https://github.com/chroma-tech/I2SClockBasedLedDriver.

I suspected maybe I copied some common code incorrectly. (As an aside, I still am unable to run both drivers, or even swap between the two at runtime without a reboot despite assigning to different I2S peripherals.)

I am running with 8 led strips definitely using RGB color order. Will hopefully be able to load and test that demo today.

**Comment by hpwit** [comment]
Hello
I see ;) I will look at your code and see what could be the issue. 
you’re not the only one wanting to merge the two drivers. 
i should do it myself and release the version

**Comment by hpwit** [comment]
Hello in the clocklessleddriver 
`Line 197
 // was nb_components (change so never have to reallocate)
            const int components = 4;
            DMABuffersTampon[0] = allocateDMABuffer(components * 8 * 2 * 3); // the buffers `
You should not have that you have put components at 4 hence 32 bits. This should be nb_components line 198 ,199,200 and remove line 197 Like in my library

**Comment by peragwin** [comment]
Awesome, not sure how that got there. Thanks for the scrutinous eye! Seems working with no issues now! Thanks!
